'use client';

import React from 'react';
import { PageHeader } from '@/components/shell/page-header';
import { Panel } from '@/components/dashboard/panel';
import { Badge } from '@/components/ui/badge';
import { Calendar } from 'lucide-react';

export default function HodClassesPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Classes Oversight"
        subtitle="Departmental view of active class sessions and timetables across all caseworkers."
        breadcrumbs={[
          { label: 'HOD', href: '/hod' },
          { label: 'Classes' },
        ]}
      />

      <Panel title="Class Sessions Timetable" description="Platform class schedule oversight">
        <div className="p-8 text-center border border-dashed border-border rounded-xl text-xs text-muted-foreground">
          <Calendar className="size-8 text-muted-foreground/60 mx-auto mb-2" />
          <p className="font-semibold text-foreground text-sm">Class Sessions Oversight</p>
          <p className="text-[11px] text-muted-foreground mt-1">Class sessions generated by Admin caseworkers across assigned families.</p>
        </div>
      </Panel>
    </div>
  );
}
